class Netflix{
 static String top10Movies[] = {"Hit Man","Four Brothers","	Mission","Mysteries of the Terracotta Warriors","Wonder","Home","Safe Home","Ultraman","How to Rob a Bank","Atlas"};
 static String englishMovies[] = {"The God Father","Pulp Fiction","Good Fellas","Alien","Rear Window","The Devil Wears Prada","The Wolf and the Lion","The Revenant","Four Brothers","Top Gun: Maverick","Spider-Man: Across the Spider-Verse","Zom 100: Bucket List of the Dead","A Silent Voice","Joker","Dune","Four Brothers","Cast Away","Baby Driver","The Old gaurd","Get Out","Cast Away","Money Ball","The King","2 Guns","The matrix"};
 static String hindiMovies[] = {"Bareilly ki Barfi","Pad Man","Mom","Udta Punjab","Dear Zindagi","Madras Cafe","Kabir Singh","The LunchBox","Barfi","Swades","Special 26","Queen","Drishyam","Pink","BaahuBali 1","BaahuBali 2","P K","Masaan","Sanju","Mimi","Mirzapur","Ugly","Dangal","Rukh","Black Friday"};
 static String kannadaMovies[] = {"Vikrant Rona","Kantara","Ek Love Ya","Love Mocktail","KGF 2","Petromax","Old Monk","James","Gaalipata","Avatara purusha","Guru Shisyaru","Window seat","Family pack","Blink","Ond sarala prema kathe","kerebete","Shakahari","Om","H2o","A","KGF","Shh","Uppi 2","Buddivanta","Ka"};
 static String koreanSeries[] = {"Sweet Home","D P","All of us are dead","Crash landing on you","Put your head on my shoulder","Goblin","My Demon","Hierarchy","Kingdom","Business Proposal","Boys","Our Beloved Summer","Twenty Five","Twenty One","Little Women","Mr Sunshine 3","The time i called you 2","Window","Lockup","Death Game","Extraordinary you","Hell Bound","Physical","Mr Sunshine","A time called You "};
 public static void main(String[] movies){
	 
 System.out.println("The Top 10 Movies are : "+top10Movies[0]+" , "+top10Movies[1]+" , "+top10Movies[2]+" , "+top10Movies[3]+" , "+top10Movies[4]+" , "+top10Movies[5]+" , "+top10Movies[6]+" , "+top10Movies[7]+" , "+top10Movies[8]+" , "+top10Movies[9]+".");
 System.out.println("The English Movies are : "+englishMovies[0]+", "+englishMovies[1]+", "+englishMovies[2]+" ,"+englishMovies[3]+", "+englishMovies[4]+", "+englishMovies[5]+" ,"+englishMovies[6]+" ,"+englishMovies[7]+" ,"+englishMovies[8]+" ,"+englishMovies[9]+" ,"+englishMovies[10]+", "+englishMovies[11]+" ,"+englishMovies[12]+", "+englishMovies[13]+" ,"+englishMovies[14]+" ,"+englishMovies[15]+", "+englishMovies[16]+" ,"+englishMovies[17]+" ,"+englishMovies[18]+", "+englishMovies[19]+" ,"+englishMovies[20]+" ,"+englishMovies[21]+", "+englishMovies[22]+" ,"+englishMovies[23]+" ,"+englishMovies[24]+".");
 System.out.println("The Hindi Movies are : "+hindiMovies[0]+", "+hindiMovies[1]+", "+hindiMovies[2]+" ,"+hindiMovies[3]+", "+hindiMovies[4]+", "+hindiMovies[5]+" ,"+hindiMovies[6]+", "+hindiMovies[7]+" ,"+hindiMovies[8]+", "+hindiMovies[9]+", "+hindiMovies[10]+" ,"+hindiMovies[11]+", "+hindiMovies[12]+", "+hindiMovies[13]+" ,"+hindiMovies[14]+" ,"+hindiMovies[15]+", "+hindiMovies[16]+" ,"+hindiMovies[17]+", "+hindiMovies[18]+" ,"+hindiMovies[19]+" ,"+hindiMovies[20]+", "+hindiMovies[21]+" ,"+hindiMovies[22]+" ,"+hindiMovies[23]+", "+hindiMovies[24]+".");
 System.out.println("The Kannada Movies are : "+kannadaMovies[0]+" ,"+kannadaMovies[1]+", "+kannadaMovies[2]+", "+kannadaMovies[3]+", "+kannadaMovies[4]+", "+kannadaMovies[5]+" ,"+kannadaMovies[6]+" ,"+kannadaMovies[7]+" "+kannadaMovies[8]+" ,"+kannadaMovies[9]+" ,"+kannadaMovies[10]+", "+kannadaMovies[11]+", "+kannadaMovies[12]+" ,"+kannadaMovies[13]+", "+kannadaMovies[14]+" ,"+kannadaMovies[15]+" ,"+kannadaMovies[16]+" ,"+kannadaMovies[17]+", "+kannadaMovies[18]+", "+kannadaMovies[19]+" ,"+kannadaMovies[20]+", "+kannadaMovies[21]+", "+kannadaMovies[22]+" ,"+kannadaMovies[23]+", "+kannadaMovies[24]+".");
 System.out.println("The Korean Series are :"+koreanSeries[0]+", "+koreanSeries[1]+" ,"+koreanSeries[2]+", "+koreanSeries[3]+" ,"+koreanSeries[4]+" ,"+koreanSeries[5]+" ,"+koreanSeries[6]+", "+koreanSeries[7]+" ,"+koreanSeries[8]+" ,"+koreanSeries[9]+" ,"+koreanSeries[10]+" ,"+koreanSeries[11]+" ,"+koreanSeries[12]+", "+koreanSeries[13]+", "+koreanSeries[14]+" ,"+koreanSeries[15]+" ,"+koreanSeries[16]+", "+koreanSeries[17]+", "+koreanSeries[18]+", "+koreanSeries[19]+" ,"+koreanSeries[20]+" "+koreanSeries[21]+", "+koreanSeries[22]+" ,"+koreanSeries[23]+", "+koreanSeries[24]+".");
   }
}